package br.com.project.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class FrmMenu extends javax.swing.JFrame {
public String userConnected;

    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/fundo.jpg"));
        Image image = icon.getImage();
        paineDesktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0,0,getWidth(),getHeight(),this);
            }
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelUserConn = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Product_ControlStock = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        screenMenu_openPDV = new javax.swing.JMenuItem();
        screenMenu_SaleDay = new javax.swing.JMenuItem();
        screenMenu_HistorySale = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        paineDesktop.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setText("Usuário conectado:");

        labelUserConn.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        labelUserConn.setForeground(new java.awt.Color(51, 153, 255));
        labelUserConn.setText("José Henrique Fernandes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUserConn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(904, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelUserConn)))
        );

        paineDesktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout paineDesktopLayout = new javax.swing.GroupLayout(paineDesktop);
        paineDesktop.setLayout(paineDesktopLayout);
        paineDesktopLayout.setHorizontalGroup(
            paineDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paineDesktopLayout.setVerticalGroup(
            paineDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paineDesktopLayout.createSequentialGroup()
                .addGap(0, 479, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setBackground(new java.awt.Color(51, 0, 51));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pessoa-alta-48 (1).png"))); // NOI18N
        jMenu1.setText("Clientes");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        jMenuItem2.setText("Controle de Clientes");
        jMenuItem2.setMaximumSize(new java.awt.Dimension(32000, 32000));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/funcionarios.png"))); // NOI18N
        jMenu2.setText("Funcionários");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2620530_check_employee_job_seeker_unemployee_icon.png"))); // NOI18N
        jMenuItem1.setText("Controle de Funcionários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fornecedores.png"))); // NOI18N
        jMenu3.setText("Fornecedores");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/103428_buy_icon.png"))); // NOI18N
        jMenuItem3.setText("Controle de Fornecedores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produtos.png"))); // NOI18N
        jMenu6.setText("Produtos");

        Product_ControlStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/49590_boxes_customers_inventory_products_icon.png"))); // NOI18N
        Product_ControlStock.setText("Controle de Estoque");
        Product_ControlStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product_ControlStockMouseClicked(evt);
            }
        });
        Product_ControlStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product_ControlStockActionPerformed(evt);
            }
        });
        jMenu6.add(Product_ControlStock);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3018582_buy_cart_checkout_products_purchase_icon.png"))); // NOI18N
        jMenuItem6.setText("Consulta de Produtos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuBar1.add(jMenu6);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vendas.png"))); // NOI18N
        jMenu4.setText("Vendas");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });

        screenMenu_openPDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/352573_in_new_open_icon (1).png"))); // NOI18N
        screenMenu_openPDV.setText("Abrir PDV");
        screenMenu_openPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenMenu_openPDVActionPerformed(evt);
            }
        });
        jMenu4.add(screenMenu_openPDV);

        screenMenu_SaleDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2682848_day_forecast_sun_sunny_weather_icon.png"))); // NOI18N
        screenMenu_SaleDay.setText("Posição do Dia");
        screenMenu_SaleDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenMenu_SaleDayActionPerformed(evt);
            }
        });
        jMenu4.add(screenMenu_SaleDay);

        screenMenu_HistorySale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4781832_ago_clock_history_report_statistics_icon.png"))); // NOI18N
        screenMenu_HistorySale.setText("Histórico de Vendas");
        screenMenu_HistorySale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenMenu_HistorySaleActionPerformed(evt);
            }
        });
        jMenu4.add(screenMenu_HistorySale);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/configuracoes.png"))); // NOI18N
        jMenu5.setText("Configurações");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2528067_avatars_groups_male_person_teamwork_icon (1).png"))); // NOI18N
        jMenuItem7.setText("Troca de Usuários");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4265055_door_exit_get_log_out_icon (1).png"))); // NOI18N
        jMenu8.setText("Sair");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paineDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paineDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmClient tela = new FrmClient();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmEmployees telaFuncionarios = new FrmEmployees();
         telaFuncionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       FrmLogin screen = new FrmLogin();
       this.dispose();
       screen.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void screenMenu_HistorySaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenMenu_HistorySaleActionPerformed
       FrmSalesHistorys screen = new FrmSalesHistorys();
       screen.setVisible(true);
    }//GEN-LAST:event_screenMenu_HistorySaleActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       this.setExtendedState(this.MAXIMIZED_BOTH);
       labelUserConn.setText(userConnected);
       this.setVisible(true);
       
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       FrmProviders screen = new FrmProviders();
       screen.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void Product_ControlStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_ControlStockMouseClicked
        FrmProducts screenProducts = new FrmProducts();
       screenProducts.setVisible(true);
    }//GEN-LAST:event_Product_ControlStockMouseClicked

    private void Product_ControlStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product_ControlStockActionPerformed
        FrmControlStock screen = new FrmControlStock();
        screen.setVisible(true);
    }//GEN-LAST:event_Product_ControlStockActionPerformed

    private void screenMenu_openPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenMenu_openPDVActionPerformed
       FrmSales screenSale = new FrmSales();
       screenSale.setVisible(true);
    }//GEN-LAST:event_screenMenu_openPDVActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       FrmProducts screenProduct1 = new FrmProducts();
       screenProduct1.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
       
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
    int op;
     op =   JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?");
     if(op == 0){
         System.exit(0);
         }
    }//GEN-LAST:event_jMenu8MouseClicked

    private void screenMenu_SaleDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenMenu_SaleDayActionPerformed
        FrmTotalSalesByDate screen = new FrmTotalSalesByDate();
        screen.setVisible(true);
    }//GEN-LAST:event_screenMenu_SaleDayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Product_ControlStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelUserConn;
    private javax.swing.JDesktopPane paineDesktop;
    public javax.swing.JMenuItem screenMenu_HistorySale;
    public javax.swing.JMenuItem screenMenu_SaleDay;
    private javax.swing.JMenuItem screenMenu_openPDV;
    // End of variables declaration//GEN-END:variables
}
